spring:
  datasource:
    username: root
    password: 2314
    url: jdbc:mysql://127.0.0.1/sec_kill
    driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: caffeine
    cache-names: SECKILL
  redisson:
    database: 1
    address: redis://127.0.0.1:6379
    connectionPoolSize: 8
    connectionMinimumIdleSize: 3
    subscriptionConnectionPoolSize: 6
    subscriptionConnectionMinimumIdleSize: 1

server:
  port: 9090
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: "sec_kill_producer"
